// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const pages: { "home": { "event": { "label": string; "target": string; "status": string }; "time": { "days": string; "hours": string; "minutes": string; "seconds": string }; "controls": { "pause": string; "reset": string; "edit": string; "settings": string }; "footer": { "timezone": string; "mode": string; "note": string } } };
  export const home: { "event": { "label": string; "target": string; "status": string }; "time": { "days": string; "hours": string; "minutes": string; "seconds": string }; "controls": { "pause": string; "reset": string; "edit": string; "settings": string }; "footer": { "timezone": string; "mode": string; "note": string } };
}
